---
version: '1'
type: documentation

component:
  name: strata-documentation
  owner: Cassini
  description: documentation
  personalDataHandling: none
  soxScope: False
  serviceClass: business-class
  paymentProcessing: False
  outOfHoursSupportRequired: False
  supportOverride:
    slackChannel: "#engineering-support"
    confluenceUrl: "https://skyscanner.atlassian.net/wiki/x/-rueJ"
